# Generated by Django 3.2.3 on 2021-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='psw_repeat',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
